name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5

      - name: Install LLVM
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "18"

      - name: Configure
        shell: bash
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DLLVM_DIR="$LLVM_PATH/lib/cmake/llvm"

      - name: Build
        run: cmake --build build --config Release

      - name: Run (macOS)
        if: runner.os == 'macOS'
        run: ./build/test-llvm

      - name: Run (Windows)
        if: runner.os == 'Windows'
        run: ./build/Release/test-llvm.exe
